---
apiVersion: ramendr.openshift.io/v1alpha1
kind: DRPlacementControl
metadata:
  name: kafka-drpc
  namespace: demo-amq
  labels:
    app: kafka-sample
spec:
  preferredCluster: sraghave-cluster2
  drPolicyRef:
    name: drpolicy-sample
  placementRef:
    kind: PlacementRule
    name: kafka-placement
  pvcSelector:
    matchLabels:
      appname: "strimzi.io/cluster: my-cluster"
